### ISSUE TITLE
How to setup MapGl to java project in Android Studio?

### ISSUE THREAD

**Issue by alisher1202** [2gis/MapGL-Android#19]
I have working project written in java using Android Studio. Now I want implement MapGl for testing my android app with 2Gis maps and features. I get API key from 2Gis support and found MapGl implementation in Kotlin, but I don't know this language and also my project fully written in Java language. It is possible to use MapGl in java project?

**Comment by nazneenhuma** [comment]
Did u find any solution? Im also stuck at the same thing

**Comment by alisher1202** [comment]
> Did u find any solution? Im also stuck at the same thing

Yes, I found a solution. MAP GL API is only in Kotlin, so you should call Kotlin code from your Java code.
This is an example:
https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html
I also created "handler class" where I did all calling functions from Kotlin. Then, I just used implementation of these "handler" class.

**Comment by lagner** [comment]
Hi all.
Call Kotlin function from java is easy. @alisher1202  has already posted a good link to start.
