### ISSUE TITLE
question: How to set bounds to map?

### ISSUE THREAD

**Issue by omurbekjk** [2gis/MapGL-Android#3]
We want to show only one city in 2gis map, how can we set borders 
when displaying 2gis map?
I found this: https://api.2gis.ru/doc/maps/1.0/manual/map/#toc-dgmap-m-34,
but not sure sdk supports it now.

**Comment by lagner** [comment]
Hi Omurbek.

Unfortunately the Android SDK does not support map bounds yet. It is a cool feature request, I’ll pass your feedback.

One more thing. The link you provided is for our old Web SDK. WebGL SDK is new and it's not compatible with previous versions.

**Comment by omurbekjk** [comment]
I like using 2gis, when can we expect next release with cool features or roadmap for this sdk?
I wanted to experiment with drawing lines for navigation between two points.

**Comment by lagner** [comment]
Hi 
Sorry for the long reply. Although don't have the road map in public yet, we have good news for you. We've done Directions plugin in the Web SDK and are preparing it for mobile right now. So you can use it with our next release. 

I think the main topic has been solved therefore I close the issue.
Feel free to create another issue if you have any questions.
