### ISSUE TITLE
Question: How to disable map rotation?

### ISSUE THREAD

**Issue by omurbekjk** [2gis/MapGL-Android#4]
I am using 2gis map in my android application and I want to disable map rotation.
How can I do it?
I could not find disabling functionality in contracts below
 ```
    var center: LonLat
    var rotation: Double // not sure what does this variable do?

    var maxZoom: Double
    var minZoom: Double
    var zoom: Double

    var maxPitch: Double
    var minPitch: Double
    var pitch : Double
```

@lagner @lastw

**Comment by lagner** [comment]
Hi @omurbekjk
You should use [disableRotationByUserInteraction](https://docs.2gis.com/ru/android/webgl/maps/reference/Map#nav-lvl1--disableRotationByUserInteraction). It does the trick
