### ISSUE TITLE
Не работает на Android 7.0 -8

### ISSUE THREAD

**Issue by AlekseevAleks** [2gis/MapGL-Android#46]
Здравствуйте.
Столкнулся с проблемой. На андроид с 7 до 8, не отобржается карта.
В логах ошибка
`Uncaught TypeError: this.mapContainer.after is not a function -- line: 2 of https://mapgl.2gis.com/api/js/v1`
Коллбек `mapReadyCallback` не вызывается.
Попробовал скачать тестовой приложение. Там тоже не отображается карта и при старте выводит ошибку:
`Detected problems with app native libraries
libavcodec.so: text relocations
libswresample.so: text relocations`

**Comment by lagner** [comment]
Добрый день.
>  На андроид с 7 до 8, не отобржается карта.

Это какие-то конкретные девайсы или может эмулятор на котором можно воспроизвести?
>Попробовал скачать тестовой приложение. Там тоже не отображается карта и при старте выводит ошибку:

[В приложении из Google Play](https://play.google.com/store/apps/details?id=ru.dublgis.dgismobile.sdktestapp&hl=ru) тоже нет карты? 
> Detected problems with app native libraries libavcodec.so: text relocations libswresample.so: text relocations

Думаю это не связано на прямую. В WebGL SDK нет нативных библиотек

**Comment by lagner** [comment]
> Uncaught TypeError: this.mapContainer.after is not a function -- line: 2 of https://mapgl.2gis.com/api/js/v1

@egoroof нет идей что тут может пойти не так?

**Comment by egoroof** [comment]
> @egoroof нет идей что тут может пойти не так?

нет идей

fyi @Trufi @artem-malko @kalyanov @alxart

**Comment by Trufi** [comment]
Такая ошибка может появляться, если используется старая версия Android System WebView. @AlekseevAleks на девайсах с ошибками, какая версия WebView установлена?

**Comment by lagner** [comment]
закрою т.к. нет достаточно информации и нет активности уже несколько месяцев
