### ISSUE TITLE
"https://dl.bintray.com/2gis/maven" Forbidden

### ISSUE THREAD

**Issue by RoizzMode** [2gis/MapGL-Android#76]
Здравствуйте!

В ReadMe для подключения зависимости указан этот репозиторий: "https://dl.bintray.com/2gis/maven", но сейчас он недоступен. Откуда можно теперь скачивать, если это вообще возможно?

**Comment by lagner** [comment]
Добрый день. 
В связи с закрытием bintray репозиторий переехал. Актуальный
```
repositories {
    maven {
        url "https://artifactory.2gis.dev/sdk-maven-release"
    }
}
```
В ближайшие дни README обновиться

**Comment by RoizzMode** [comment]
Благодарю! Все скачалось =)
