### ISSUE TITLE
Кэширование

### ISSUE THREAD

**Issue by hlystovov** [2gis/MapGL-Android#82]
У меня написано Android приложение, которое использует Google sdk и OpenStreetMap sdk для работы с картами. И в Google sdk и в OpenStreetMap sdk настроено кэширование. Отключаешь интернет, нажимаешь назад (т.е. выходишь из работы с картой), потом обратно входишь на работу с картой и нормально подгружаются картинки тайлов. Подключил 2GIS. И тут то же самое не работает. Почему не работает кэширование? Или как заставить 2GIS, чтобы оно работало?

**Comment by lagner** [comment]
Добрый день. Это Web версия карт которая работает в браузере и сейчас в ней нет возможности работать offline. Добавлять такую возможность в ближайшее время не планируем. 

Если кэширование необходимо, предлагаю использовать нативный SDK. По ссылке ниже можно ознакомиться с возможностями. 
https://docs.2gis.com/ru/android/sdk/overview
Нативный SDK дает возможность кэшировать тайлы карты. Параметры кэша задаются во время конфигурации SDK
